# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img = QtWidgets.QLabel(self.centralwidget)
        self.img.setGeometry(QtCore.QRect(310, 10, 361, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img.sizePolicy().hasHeightForWidth())
        self.img.setSizePolicy(sizePolicy)
        self.img.setScaledContents(False)
        self.img.setObjectName("img")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.importFile = QtWidgets.QPushButton(self.centralwidget)
        self.importFile.setGeometry(QtCore.QRect(84, 40, 91, 23))
        self.importFile.setObjectName("importFile")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 70, 221, 91))
        self.widget.setObjectName("widget")
        self.eyesCheck = QtWidgets.QCheckBox(self.widget)
        self.eyesCheck.setGeometry(QtCore.QRect(0, 10, 61, 17))
        self.eyesCheck.setObjectName("eyesCheck")
        self.lipsCheck = QtWidgets.QCheckBox(self.widget)
        self.lipsCheck.setGeometry(QtCore.QRect(0, 40, 61, 17))
        self.lipsCheck.setObjectName("lipsCheck")
        self.pickEyesColor = QtWidgets.QPushButton(self.widget)
        self.pickEyesColor.setGeometry(QtCore.QRect(80, 10, 81, 23))
        self.pickEyesColor.setObjectName("pickEyesColor")
        self.pickLipsColor = QtWidgets.QPushButton(self.widget)
        self.pickLipsColor.setGeometry(QtCore.QRect(80, 40, 81, 23))
        self.pickLipsColor.setObjectName("pickLipsColor")
        self.eyesColorShower = QtWidgets.QLabel(self.widget)
        self.eyesColorShower.setGeometry(QtCore.QRect(170, 11, 21, 20))
        self.eyesColorShower.setText("")
        self.eyesColorShower.setObjectName("eyesColorShower")
        self.lipsColorShower = QtWidgets.QLabel(self.widget)
        self.lipsColorShower.setGeometry(QtCore.QRect(170, 40, 21, 20))
        self.lipsColorShower.setText("")
        self.lipsColorShower.setObjectName("lipsColorShower")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.img.setText(_translate("MainWindow", "TextLabel"))
        self.importFile.setText(_translate("MainWindow", "Выбрать файл"))
        self.eyesCheck.setText(_translate("MainWindow", "Глаза"))
        self.lipsCheck.setText(_translate("MainWindow", "Губы"))
        self.pickEyesColor.setText(_translate("MainWindow", "Выбрать цвет"))
        self.pickLipsColor.setText(_translate("MainWindow", "Выбрать цвет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
